### ISSUE TITLE
How are with MSGE7 without the sparkfun shield?

### ISSUE THREAD

**Issue by ghost** [the-red-team/Arduino-FastLED-Music-Visualizer#2]
Hi, I have some MSGEQ7'S but no sparkfun shield. could you please elaborate as to how to wire it up without it?

int strobe = 4;
int reset = 5;
int audio1 = A0;
int audio2 = A1;
int left[7];
int right[7];
int band;
int audio_input = 0;
int freq = 0

what does int freq, int band, and int left and right refer to?

thanks

**Comment by justcallmekoko** [comment]
Regarding the MSGEQ7, you can find the schematic to the spectrum shield on the sparkfun website and how the pins of the shield relate to the pinout of the MSGEQ7.

https://cdn.sparkfun.com/datasheets/Dev/Arduino/Shields/Spectrum_Shield_v16.pdf

int left and int right are arrays which hold the analog reading of the 7 bands in both the left and right audio. int band is a global variable which is used to iterate over the 7 bands of audio frequencies after reading the shield. int freq refers to which band the code uses to visualize the music. In this case the code is tracking band 0 which is the lowest of the audio frequencies being read. That is why the visualization is reactive only to bass frequencies.
